### ISSUE TITLE
Does your code support python3.8?

### ISSUE THREAD

**Issue by HackYardo** [wsdd2/PikachuGo#2]
When I pip .txt, it turns to:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Comment by wsdd2** [comment]
No, only support python 2.7.15



发自我的iPhone


------------------ Original ------------------
